version: "3"
services:
  web:
    build:
      context: .
      args:
        http_proxy:   ${http_proxy}
        https_proxy:  ${https_proxy}
    command: python3 manage.py runserver 0.0.0.0:8000
    environment:
      http_proxy:   ${http_proxy}
      https_proxy:  ${https_proxy}
      PYTHONPATH:   /code
    volumes:
      - ./code:/code
    ports:
      - 8000:8000
